// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBancario.Data;

#nullable disable

namespace SistemaBancario.Data.Migrations
{
    [DbContext(typeof(SistemaBancarioContext))]
    [Migration("20240630044301_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SistemaBancario.Model.ContaCorrente", b =>
                {
                    b.Property<string>("IdContaCorrente")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdContaCorrente");

                    b.ToTable("ContaCorrente");

                    b.HasData(
                        new
                        {
                            IdContaCorrente = "B6BAFC09-6967-ED11-A567-055DFA4A16C9",
                            Ativo = 1,
                            Nome = "Katherine Sanchez",
                            Numero = 123
                        },
                        new
                        {
                            IdContaCorrente = "FA99D033-7067-ED11-96C6-7C5DFA4A16C9",
                            Ativo = 1,
                            Nome = "Eva Woodward",
                            Numero = 456
                        },
                        new
                        {
                            IdContaCorrente = "382D323D-7067-ED11-8866-7D5DFA4A16C9",
                            Ativo = 1,
                            Nome = "Tevin Mcconnell",
                            Numero = 789
                        },
                        new
                        {
                            IdContaCorrente = "F475F943-7067-ED11-A06B-7E5DFA4A16C9",
                            Ativo = 0,
                            Nome = "Ameena Lynn",
                            Numero = 741
                        },
                        new
                        {
                            IdContaCorrente = "BCDACA4A-7067-ED11-AF81-825DFA4A16C9",
                            Ativo = 0,
                            Nome = "Jarrad Mckee",
                            Numero = 852
                        },
                        new
                        {
                            IdContaCorrente = "D2E02051-7067-ED11-94C0-835DFA4A16C9",
                            Ativo = 0,
                            Nome = "Elisha Simons",
                            Numero = 963
                        });
                });

            modelBuilder.Entity("SistemaBancario.Model.Idempotencia", b =>
                {
                    b.Property<string>("ChaveIdempotencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("Idempotencia");
                });

            modelBuilder.Entity("SistemaBancario.Model.Movimento", b =>
                {
                    b.Property<string>("IdMovimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataMovimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("Movimento");
                });

            modelBuilder.Entity("SistemaBancario.Model.Movimento", b =>
                {
                    b.HasOne("SistemaBancario.Model.ContaCorrente", "ContaCorrente")
                        .WithMany()
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });
#pragma warning restore 612, 618
        }
    }
}
